# The Impacts of AI on Company Structure

In [15]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shutil

In [16]:
df = pd.read_csv("../data/tech_layoffs_2026_tracker.csv")
df.head()

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,4000,14000,CNBC / NetworkWorld,January 2026,Q1 2026,North America,Mega (5K+),Positive,1.03,"March 18, 2026"
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.00,"March 18, 2026"
2,Meta Reality Labs,2026-01-20,1500,10.0,Social Media/VR,USA,Menlo Park,True,Pivot from metaverse to AI research,164.5,...,0,500,InformationWeek / NYT,January 2026,Q1 2026,North America,Medium (500-2K),Positive,1.90,"March 18, 2026"
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,...,0,500,TechRepublic / Metaintro,March 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,10.00,"March 18, 2026"
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,6000,10000,IBTimes,February 2026,Q1 2026,North America,Mega (5K+),Positive,15.00,"March 18, 2026"

## EDA

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company                        28 non-null     object
 1   layoff_date                    28 non-null     object
 2   jobs_cut                       28 non-null     int64
 3   pct_workforce_cut              28 non-null     float64
 4   sector                         28 non-null     object
 5   country                        28 non-null     object
 6   hq_city                        28 non-null     object
 7   ai_cited                       28 non-null     bool
 8   reason_stated                  28 non-null     object
 9   company_revenue_2025_bn        28 non-null     float64
 10  pre_layoff_headcount           28 non-null     int64
 11  stock_change_day_pct           28 non-null     float64
 12  simultaneous_ai_investment_bn  28 non-null     float64
 13  roles_most_affected            28 non-null     object
 14  replacement_roles              28 non-null     object
 15  ceo_quote                      28 non-null     object
 16  layoffs_2024                   28 non-null     int64
 17  layoffs_2025                   28 non-null     int64
 18  verified_source                28 non-null     object
 19  month                          28 non-null     object
 20  quarter                        28 non-null     object
 21  region                         28 non-null     object
 22  layoff_size_category           28 non-null     object
 23  stock_reaction                 28 non-null     object
 24  laid_off_vs_headcount_pct      28 non-null     float64
 25  data_as_of                     28 non-null     object
dtypes: bool(1), float64(5), int64(4), object(16)
memory usage: 5.6+ KB

In [18]:
df.dtypes

company                           object
layoff_date                       object
jobs_cut                           int64
pct_workforce_cut                float64
sector                            object
country                           object
hq_city                           object
ai_cited                            bool
reason_stated                     object
company_revenue_2025_bn          float64
pre_layoff_headcount               int64
stock_change_day_pct             float64
simultaneous_ai_investment_bn    float64
roles_most_affected               object
replacement_roles                 object
ceo_quote                         object
layoffs_2024                       int64
layoffs_2025                       int64
verified_source                   object
month                             object
quarter                           object
region                            object
layoff_size_category              object
stock_reaction                    object
laid_off_vs_headcount_pct        float64
data_as_of                        object
dtype: object

In [21]:
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "missing": df.isnull().sum(),
    "unique": df.nunique()
})
summary

                                  dtype  missing  unique
company                          object        0      27
layoff_date                      object        0      23
jobs_cut                          int64        0      18
pct_workforce_cut               float64        0      18
sector                           object        0      23
country                          object        0      10
hq_city                          object        0      20
ai_cited                           bool        0       2
reason_stated                    object        0      28
company_revenue_2025_bn         float64        0      24
pre_layoff_headcount              int64        0      25
stock_change_day_pct            float64        0      22
simultaneous_ai_investment_bn   float64        0      15
roles_most_affected              object        0      27
replacement_roles                object        0      18
ceo_quote                        object        0      28
layoffs_2024                      int64        0       9
layoffs_2025                      int64        0      13
verified_source                  object        0      15
month                            object        0       3
quarter                          object        0       1
region                           object        0       3
layoff_size_category           category        0       4
stock_reaction                 category        0       3
laid_off_vs_headcount_pct       float64        0      27
data_as_of                       object        0       1

### Cleaning up Data Type
Stock Reaction: this category seems to have two outcomes "positive" or "negative" so it makes the most sense to save space and change the values to a categorical

Layoff Size Category: Category being in the name kind of gave this one away, but it helps to have this as a categorical for modeling purposes

In [19]:
df['stock_reaction'] = df['stock_reaction'].astype('category')
df['layoff_size_category'] = df['layoff_size_category'].astype('category')